### ISSUE TITLE
December number of days

### ISSUE THREAD

**Issue by Aldrein** [schuhmaj/nasa-breakup-model-cpp#44]
Indicated only 30 days in December instead of 31 (as mentioned in the comment)
https://github.com/schuhmaj/nasa-breakup-model-cpp/blob/79304c69ddf8b0108a9e78524e85c7325a764c34/src/breakupModel/model/OrbitalElements.h#L64C18-L64C20

**Comment by schuhmaj** [comment]
Good catch! Thanks for reporting the issue. It will be fixed in the main repository via https://github.com/esa/NASA-breakup-model-cpp/pull/7
